<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.16.3 by Michael Rose
  Copyright 2013-2019 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Exception handling particulars in C# - Wayneâ€™s Geek Life</title>
<meta name="description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:So the difference is, &quot;throw ex&quot; will truncate&nbsp;the StackTrace information where it was originally thrown (this will cause the so called issue - &quot;breaking the stack&quot;), but &quot;throw&quot; will contain all the information.Delve deeper, &quot;throw ex&quot; in IL level essentially indicates &quot;rethrow&quot;, whereas &quot;throw&quot; indicate &quot;throw&quot;, please see their IL code below: .method public hidebysig static void MethodThrowException1() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: rethrow  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f } .method public hidebysig static void MethodThrowException2() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: ldloc.0  &nbsp;&nbsp;&nbsp; L_000e: throw  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f }&nbsp;The definition for &quot;rethrow&quot; and &quot;throw&quot; in IL are showing below:rethrow: Rethrows the current exception.throw: Throws the exception Object currently on evaluation stack.So what should we do?Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException: try { &nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); } catch (DummyException de) { &nbsp;&nbsp;&nbsp; AnotherTypeOfException anotherTypeOfException = new AnotherTypeOfException(&quot;Customized exception message.&quot;, de) &nbsp;&nbsp;&nbsp; throw anotherTypeOfException; }When initializes AnotherTypeOfException&nbsp;we actually calls Exception&#39;s construcor &quot;(String message, Exception innerException)&quot;, so finally there will be&nbsp;no information loss.There is one&nbsp;particular&nbsp;details,&nbsp;when we wrote code similar with below, Resharper will warning us it is redundant, because &quot;The catch statement may appear to be doing something, but it really isn&#39;t: all it&#39;s doing is throwing the exception (with the same stack information)&quot;,&nbsp;Resharper link.&nbsp;&nbsp;&nbsp;Instead, if we wrote &quot;throw de&quot;, in the above example, Resharper will NOT give you any warning, because now we know they are different,&nbsp;&quot;throw de&quot; will&nbsp;truncate the StackTrace information and rethrow the&nbsp;DemmyException&nbsp;instance.&nbsp;Different between parameterless&nbsp;catch and catch (Exception ex)&nbsp;Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from&nbsp;System.Exception, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those&nbsp;Non-CLS-Compliant exceptions into an specific Exception type:&nbsp;RuntimeWrappedException,&nbsp;it has a property:&nbsp;WrappedException&nbsp;to store a non-CLS-Compliant exception, results in statement &quot;catch (Exception ex)&quot; can catch all runtime exceptions.Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying&nbsp;RuntimeCompatibility&nbsp;attribute to your assembly, i.e. AssemblyInfo.cs.[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to&nbsp;System.Exception, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.&nbsp;&nbsp;Further reading&nbsp;&nbsp;Exception Handling on MSDNhttp://msdn.microsoft.com/en-us/library/ms229005.aspxUsing COM Objecthttp://insideaspnet.com/index/using-com-objects/&nbsp;Difference between &quot;throw&quot; and &quot;throw ex&quot; in .NEThttp://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspxAlso posted at my blog - Wayne&#39;s Geek Life:&nbsp;http://wayneye.com/Blog/Different-Between-Throw-Throw-EX&nbsp;&nbsp;Also posted on CodeProject:&nbsp;http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="Wayne's Geek Life">
<meta property="og:title" content="Exception handling particulars in C#">
<meta property="og:url" content="https://wayneye.com/Exception-Handling-Particulars-In-Csharp">


  <meta property="og:description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:So the difference is, &quot;throw ex&quot; will truncate&nbsp;the StackTrace information where it was originally thrown (this will cause the so called issue - &quot;breaking the stack&quot;), but &quot;throw&quot; will contain all the information.Delve deeper, &quot;throw ex&quot; in IL level essentially indicates &quot;rethrow&quot;, whereas &quot;throw&quot; indicate &quot;throw&quot;, please see their IL code below: .method public hidebysig static void MethodThrowException1() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: rethrow  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f } .method public hidebysig static void MethodThrowException2() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: ldloc.0  &nbsp;&nbsp;&nbsp; L_000e: throw  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f }&nbsp;The definition for &quot;rethrow&quot; and &quot;throw&quot; in IL are showing below:rethrow: Rethrows the current exception.throw: Throws the exception Object currently on evaluation stack.So what should we do?Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException: try { &nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); } catch (DummyException de) { &nbsp;&nbsp;&nbsp; AnotherTypeOfException anotherTypeOfException = new AnotherTypeOfException(&quot;Customized exception message.&quot;, de) &nbsp;&nbsp;&nbsp; throw anotherTypeOfException; }When initializes AnotherTypeOfException&nbsp;we actually calls Exception&#39;s construcor &quot;(String message, Exception innerException)&quot;, so finally there will be&nbsp;no information loss.There is one&nbsp;particular&nbsp;details,&nbsp;when we wrote code similar with below, Resharper will warning us it is redundant, because &quot;The catch statement may appear to be doing something, but it really isn&#39;t: all it&#39;s doing is throwing the exception (with the same stack information)&quot;,&nbsp;Resharper link.&nbsp;&nbsp;&nbsp;Instead, if we wrote &quot;throw de&quot;, in the above example, Resharper will NOT give you any warning, because now we know they are different,&nbsp;&quot;throw de&quot; will&nbsp;truncate the StackTrace information and rethrow the&nbsp;DemmyException&nbsp;instance.&nbsp;Different between parameterless&nbsp;catch and catch (Exception ex)&nbsp;Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from&nbsp;System.Exception, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those&nbsp;Non-CLS-Compliant exceptions into an specific Exception type:&nbsp;RuntimeWrappedException,&nbsp;it has a property:&nbsp;WrappedException&nbsp;to store a non-CLS-Compliant exception, results in statement &quot;catch (Exception ex)&quot; can catch all runtime exceptions.Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying&nbsp;RuntimeCompatibility&nbsp;attribute to your assembly, i.e. AssemblyInfo.cs.[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to&nbsp;System.Exception, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.&nbsp;&nbsp;Further reading&nbsp;&nbsp;Exception Handling on MSDNhttp://msdn.microsoft.com/en-us/library/ms229005.aspxUsing COM Objecthttp://insideaspnet.com/index/using-com-objects/&nbsp;Difference between &quot;throw&quot; and &quot;throw ex&quot; in .NEThttp://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspxAlso posted at my blog - Wayne&#39;s Geek Life:&nbsp;http://wayneye.com/Blog/Different-Between-Throw-Throw-EX&nbsp;&nbsp;Also posted on CodeProject:&nbsp;http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">





  <meta name="twitter:site" content="@wayneye">
  <meta name="twitter:title" content="Exception handling particulars in C#">
  <meta name="twitter:description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:So the difference is, &quot;throw ex&quot; will truncate&nbsp;the StackTrace information where it was originally thrown (this will cause the so called issue - &quot;breaking the stack&quot;), but &quot;throw&quot; will contain all the information.Delve deeper, &quot;throw ex&quot; in IL level essentially indicates &quot;rethrow&quot;, whereas &quot;throw&quot; indicate &quot;throw&quot;, please see their IL code below: .method public hidebysig static void MethodThrowException1() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: rethrow  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f } .method public hidebysig static void MethodThrowException2() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: ldloc.0  &nbsp;&nbsp;&nbsp; L_000e: throw  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f }&nbsp;The definition for &quot;rethrow&quot; and &quot;throw&quot; in IL are showing below:rethrow: Rethrows the current exception.throw: Throws the exception Object currently on evaluation stack.So what should we do?Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException: try { &nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); } catch (DummyException de) { &nbsp;&nbsp;&nbsp; AnotherTypeOfException anotherTypeOfException = new AnotherTypeOfException(&quot;Customized exception message.&quot;, de) &nbsp;&nbsp;&nbsp; throw anotherTypeOfException; }When initializes AnotherTypeOfException&nbsp;we actually calls Exception&#39;s construcor &quot;(String message, Exception innerException)&quot;, so finally there will be&nbsp;no information loss.There is one&nbsp;particular&nbsp;details,&nbsp;when we wrote code similar with below, Resharper will warning us it is redundant, because &quot;The catch statement may appear to be doing something, but it really isn&#39;t: all it&#39;s doing is throwing the exception (with the same stack information)&quot;,&nbsp;Resharper link.&nbsp;&nbsp;&nbsp;Instead, if we wrote &quot;throw de&quot;, in the above example, Resharper will NOT give you any warning, because now we know they are different,&nbsp;&quot;throw de&quot; will&nbsp;truncate the StackTrace information and rethrow the&nbsp;DemmyException&nbsp;instance.&nbsp;Different between parameterless&nbsp;catch and catch (Exception ex)&nbsp;Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from&nbsp;System.Exception, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those&nbsp;Non-CLS-Compliant exceptions into an specific Exception type:&nbsp;RuntimeWrappedException,&nbsp;it has a property:&nbsp;WrappedException&nbsp;to store a non-CLS-Compliant exception, results in statement &quot;catch (Exception ex)&quot; can catch all runtime exceptions.Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying&nbsp;RuntimeCompatibility&nbsp;attribute to your assembly, i.e. AssemblyInfo.cs.[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to&nbsp;System.Exception, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.&nbsp;&nbsp;Further reading&nbsp;&nbsp;Exception Handling on MSDNhttp://msdn.microsoft.com/en-us/library/ms229005.aspxUsing COM Objecthttp://insideaspnet.com/index/using-com-objects/&nbsp;Difference between &quot;throw&quot; and &quot;throw ex&quot; in .NEThttp://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspxAlso posted at my blog - Wayne&#39;s Geek Life:&nbsp;http://wayneye.com/Blog/Different-Between-Throw-Throw-EX&nbsp;&nbsp;Also posted on CodeProject:&nbsp;http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">
  <meta name="twitter:url" content="https://wayneye.com/Exception-Handling-Particulars-In-Csharp">

  
    <meta name="twitter:card" content="summary">
    
  

  



  <meta property="article:published_time" content="2011-07-08T00:00:00-07:00">





  

  
    <meta property="fb:app_id" content="374223339969060">
  


<link rel="canonical" href="https://wayneye.com/Exception-Handling-Particulars-In-Csharp">













<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="Wayne's Geek Life Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">

<!--[if IE ]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->
<link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon/favicon-16x16.png">
<link rel="manifest" href="assets/images/favicon/site.webmanifest">
<link rel="mask-icon" href="assets/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

<!-- end custom head snippets -->

  </head>

  <body class="layout--single wide">

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
        <a class="site-title" href="/">Wayne's Geek Life</a>
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/categories/" >Categories</a>
            </li><li class="masthead__menu-item">
              <a href="/tags/" >Tags</a>
            </li><li class="masthead__menu-item">
              <a href="/search/" >Search</a>
            </li><li class="masthead__menu-item">
              <a href="/album/" >Album</a>
            </li><li class="masthead__menu-item">
              <a href="/about/" >About</a>
            </li></ul>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  


<div itemscope itemtype="https://schema.org/Person">

  
    <div class="author__avatar">
      

      
        <img src="/assets/images/me.jpg" alt="Wayne Ye" itemprop="image">
      
    </div>
  

  <div class="author__content">
    
      <h3 class="author__name" itemprop="name">Wayne Ye</h3>
    
    
      <p class="author__bio" itemprop="description">
        Whatever is worth doing is worth doing well!
      </p>
    
  </div>

  <div class="author__urls-wrapper">
    <button class="btn btn--inverse">Follow</button>
    <ul class="author__urls social-icons">
      
        <li itemprop="homeLocation" itemscope itemtype="https://schema.org/Place">
          <i class="fas fa-fw fa-map-marker-alt" aria-hidden="true"></i> <span itemprop="name">San Francisco</span>
        </li>
      

      
        
          
            <li><a href="mailto:me@wayneye.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
          
        
          
            <li><a href="https://wayneye.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-link" aria-hidden="true"></i> Website</a></li>
          
        
          
            <li><a href="https://twitter.com/wayneye" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i> Twitter</a></li>
          
        
          
            <li><a href="https://facebook.com/WayneYeDotCom" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
          
        
          
            <li><a href="https://github.com/WayneYe/" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub</a></li>
          
        
      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      <!--
  <li>
    <a href="http://link-to-whatever-social-network.com/user/" itemprop="sameAs" rel="nofollow noopener noreferrer">
      <i class="fas fa-fw" aria-hidden="true"></i> Custom Social Profile Link
    </a>
  </li>
-->
    </ul>
  </div>
</div>

  
  </div>


  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Exception handling particulars in C#">
    <meta itemprop="description" content="BackgroundException handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;Differences between throw and throw ex&nbsp;I guess every C# developer has seen code snippet below: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw ex; }In the catch block, we can rethrow the caught exception instance of IOException&nbsp;to higher level, and we may also saw another way in a little different: try { &nbsp;&nbsp;&nbsp; // Do some work, exception occurs } catch (IOException ex) { &nbsp;&nbsp;&nbsp; // Exception caught, re-throw it to bubble up &nbsp;&nbsp;&nbsp; throw; }Is there any different?&nbsp;The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException. internal class DummyException : Exception { &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public DummyException(String dummymsg, Exception innerException) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : base(dummymsg, innerException) &nbsp;&nbsp;&nbsp; {  &nbsp;&nbsp;&nbsp; } }&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above: class Program { &nbsp;&nbsp;&nbsp; private static void DoLowLevelOperation() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Do some low level operation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; public static void MethodThrowException1() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; public static void MethodThrowException2() &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DoLowLevelOperation(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw de; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp; static void Main(string[] args) &nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException1(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de1.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MethodThrowException2(); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (DummyException de2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.Message); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Console.WriteLine(de2.StackTrace); &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } &nbsp;&nbsp;&nbsp; } }&nbsp;The result will be:So the difference is, &quot;throw ex&quot; will truncate&nbsp;the StackTrace information where it was originally thrown (this will cause the so called issue - &quot;breaking the stack&quot;), but &quot;throw&quot; will contain all the information.Delve deeper, &quot;throw ex&quot; in IL level essentially indicates &quot;rethrow&quot;, whereas &quot;throw&quot; indicate &quot;throw&quot;, please see their IL code below: .method public hidebysig static void MethodThrowException1() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: rethrow  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f } .method public hidebysig static void MethodThrowException2() cil managed { &nbsp;&nbsp;&nbsp; .maxstack 1 &nbsp;&nbsp;&nbsp; .locals init ( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0] class ConsoleUnitTest.DummyException de) &nbsp;&nbsp;&nbsp; L_0000: nop  &nbsp;&nbsp;&nbsp; L_0001: nop  &nbsp;&nbsp;&nbsp; L_0002: call void ConsoleUnitTest.Program::DoLowLevelOperation() &nbsp;&nbsp;&nbsp; L_0007: nop  &nbsp;&nbsp;&nbsp; L_0008: nop  &nbsp;&nbsp;&nbsp; L_0009: leave.s L_000f &nbsp;&nbsp;&nbsp; L_000b: stloc.0  &nbsp;&nbsp;&nbsp; L_000c: nop  &nbsp;&nbsp;&nbsp; L_000d: ldloc.0  &nbsp;&nbsp;&nbsp; L_000e: throw  &nbsp;&nbsp;&nbsp; L_000f: nop  &nbsp;&nbsp;&nbsp; L_0010: ret  &nbsp;&nbsp;&nbsp; .try L_0001 to L_000b catch ConsoleUnitTest.DummyException handler L_000b to L_000f }&nbsp;The definition for &quot;rethrow&quot; and &quot;throw&quot; in IL are showing below:rethrow: Rethrows the current exception.throw: Throws the exception Object currently on evaluation stack.So what should we do?Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException: try { &nbsp;&nbsp;&nbsp; throw new DummyException(&quot;A dummy exception message!&quot;); } catch (DummyException de) { &nbsp;&nbsp;&nbsp; AnotherTypeOfException anotherTypeOfException = new AnotherTypeOfException(&quot;Customized exception message.&quot;, de) &nbsp;&nbsp;&nbsp; throw anotherTypeOfException; }When initializes AnotherTypeOfException&nbsp;we actually calls Exception&#39;s construcor &quot;(String message, Exception innerException)&quot;, so finally there will be&nbsp;no information loss.There is one&nbsp;particular&nbsp;details,&nbsp;when we wrote code similar with below, Resharper will warning us it is redundant, because &quot;The catch statement may appear to be doing something, but it really isn&#39;t: all it&#39;s doing is throwing the exception (with the same stack information)&quot;,&nbsp;Resharper link.&nbsp;&nbsp;&nbsp;Instead, if we wrote &quot;throw de&quot;, in the above example, Resharper will NOT give you any warning, because now we know they are different,&nbsp;&quot;throw de&quot; will&nbsp;truncate the StackTrace information and rethrow the&nbsp;DemmyException&nbsp;instance.&nbsp;Different between parameterless&nbsp;catch and catch (Exception ex)&nbsp;Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from&nbsp;System.Exception, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those&nbsp;Non-CLS-Compliant exceptions into an specific Exception type:&nbsp;RuntimeWrappedException,&nbsp;it has a property:&nbsp;WrappedException&nbsp;to store a non-CLS-Compliant exception, results in statement &quot;catch (Exception ex)&quot; can catch all runtime exceptions.Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying&nbsp;RuntimeCompatibility&nbsp;attribute to your assembly, i.e. AssemblyInfo.cs.[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to&nbsp;System.Exception, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.&nbsp;&nbsp;Further reading&nbsp;&nbsp;Exception Handling on MSDNhttp://msdn.microsoft.com/en-us/library/ms229005.aspxUsing COM Objecthttp://insideaspnet.com/index/using-com-objects/&nbsp;Difference between &quot;throw&quot; and &quot;throw ex&quot; in .NEThttp://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspxAlso posted at my blog - Wayne&#39;s Geek Life:&nbsp;http://wayneye.com/Blog/Different-Between-Throw-Throw-EX&nbsp;&nbsp;Also posted on CodeProject:&nbsp;http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">
    <meta itemprop="datePublished" content="July 08, 2011">
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Exception handling particulars in C#
</h1>
          
            <p class="page__meta"><i class="far fa-clock" aria-hidden="true"></i> 




  4 minute read
</p>
          
        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right ">
            <nav class="toc">
              <header><h4 class="nav__title"><i class="fas fa-cog"></i> On this page</h4></header>
              <ul class="toc__menu">
  <li><a href="#">Background</a></li>
  <li><a href="#">Differences between throw and throw exÂ </a></li>
  <li><a href="#">Is there any different?Â </a></li>
  <li><a href="#">Different between parameterlessÂ catch and catch (Exception ex)Â </a></li>
  <li><a href="#">Further readingÂ Â </a></li>
</ul>
            </nav>
          </aside>
        
        <h3>Background</h3>
<p>Exception handling appears in most .NET applications, this post is trying to describe some &nbsp;Exception handling particulars in C# which might not take enough awareness from C# developers.&nbsp;</p>
<h3>Differences between throw and throw ex&nbsp;</h3>
<p>I guess every C# developer has seen code snippet below:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #7f9f7f;">// Do some work, exception occurs</span><br /> <span style="color: #dcdccc;">}</span><br /> <span style="color: #e3ceab;">catch</span> (IO<span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">ex</span>)<br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #7f9f7f;">// Exception caught, re-throw it to bubble up</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">ex</span>;<br /> <span style="color: #dcdccc;">}</span></pre>
<p>In the <code>catch</code> block, we can rethrow the caught exception instance of <code>IOException&nbsp;</code>to higher level, and we may also saw another way in a little different:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #7f9f7f;">// Do some work, exception occurs</span><br /> <span style="color: #dcdccc;">}</span><br /> <span style="color: #e3ceab;">catch</span> (IO<span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">ex</span>)<br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #7f9f7f;">// Exception caught, re-throw it to bubble up</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span>;<br /> <span style="color: #dcdccc;">}</span></pre>
<h3><strong>Is there any different?&nbsp;</strong></h3>
<p>The answer is yes! To prove that I wrote a simple snippet of code below, first is a simple customized Exception: DummyException.</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">internal</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">Exception</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">public</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #dcdccc;">String</span> <span style="color: #dcdccc;">dummymsg</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">base</span>(<span style="color: #dcdccc;">dummymsg</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">public</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #dcdccc;">String</span> <span style="color: #dcdccc;">dummymsg</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">Exception</span> <span style="color: #dcdccc;">innerException</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">base</span>(<span style="color: #dcdccc;">dummymsg</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">innerException</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <span style="color: #dcdccc;">}</span></pre>
<p>&nbsp;And then I manually throw the DummyException within one method, while handle it in different way mentioned above:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">Program</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">private</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">DoLowLevelOperation</span>()<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #7f9f7f;">// Do some low level operation</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span> <span style="color: #e3ceab;">new</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #cc9393;">"A dummy exception message!"</span>);<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">public</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">MethodThrowException1</span>()<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">try</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">DoLowLevelOperation</span>();<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span>;<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">public</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">MethodThrowException2</span>()<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">try</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">DoLowLevelOperation</span>();<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">de</span>;<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #efef8f;">Main</span>(<span style="color: #dfdfbf; font-weight: bold;">string</span><span style="color: #dcdccc;">[]</span> <span style="color: #dcdccc;">args</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">try</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">MethodThrowException1</span>();<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de1</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de1</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Message</span>);<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de1</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">StackTrace</span>);<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">try</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">MethodThrowException2</span>();<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de2</span>)<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de2</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Message</span>);<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">Console</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">WriteLine</span>(<span style="color: #dcdccc;">de2</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">StackTrace</span>);<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">}</span><br /> <span style="color: #dcdccc;">}</span></pre>
<p>&nbsp;The result will be:</p>
<p><!--more--></p>
<p><img title="Exception handling" src="https://byfiles.storage.live.com/y1pOsmopqaR3U4_pOpoKta9ao4On0IrEWZf78M-fGOIROnhl0nPaFzDEJSeykT3-jL8fBn5YBddITP0rM9qzZU3qg/EXHandling.png?psid=1" alt="Exception handling" width="677" height="442" /></p>
<p>So the difference is, "throw ex" will truncate&nbsp;the StackTrace information where it was originally thrown (this will cause the so called issue - "breaking the stack"), but "throw" will contain all the information.</p>
<p>Delve deeper, "throw ex" in IL level essentially indicates "<strong>rethrow</strong>", whereas "throw" indicate "<strong>throw</strong>", please see their IL code below:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">method</span> <span style="color: #e3ceab;">public</span> <span style="color: #dcdccc;">hidebysig</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">MethodThrowException1</span>() <span style="color: #dcdccc;">cil</span> <span style="color: #dcdccc;">managed</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">maxstack</span> <span style="color: #8cd0d3;">1</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">locals</span> <span style="color: #dcdccc;">init</span> (<br /> <span style="color: #efef8f;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0000</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0001</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0002</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">call</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Program</span><span style="color: #dcdccc;">::</span><span style="color: #dcdccc;">DoLowLevelOperation</span>()<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0007</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0008</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0009</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">leave</span><span style="color: #dcdccc;">.</span>s <span style="color: #dcdccc;">L_000f</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000b</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">stloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000c</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000d</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">rethrow</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000f</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0010</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ret</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #e3ceab;">try</span> <span style="color: #dcdccc;">L_0001</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #e3ceab;">catch</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">handler</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000f</span><br /> <span style="color: #dcdccc;">}</span></pre>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">method</span> <span style="color: #e3ceab;">public</span> <span style="color: #dcdccc;">hidebysig</span> <span style="color: #e3ceab;">static</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">MethodThrowException2</span>() <span style="color: #dcdccc;">cil</span> <span style="color: #dcdccc;">managed</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">maxstack</span> <span style="color: #8cd0d3;">1</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">locals</span> <span style="color: #dcdccc;">init</span> (<br /> <span style="color: #efef8f;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</span> <span style="color: #e3ceab;">class</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0000</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0001</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0002</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">call</span> <span style="color: #e3ceab;">void</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">Program</span><span style="color: #dcdccc;">::</span><span style="color: #dcdccc;">DoLowLevelOperation</span>()<br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0007</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0008</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0009</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">leave</span><span style="color: #dcdccc;">.</span>s <span style="color: #dcdccc;">L_000f</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000b</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">stloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000c</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000d</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ldloc</span><span style="color: #dcdccc;">.</span><span style="color: #8cd0d3;">0</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000e</span><span style="color: #dcdccc;">:</span> <span style="color: #e3ceab;">throw</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_000f</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">nop</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">L_0010</span><span style="color: #dcdccc;">:</span> <span style="color: #dcdccc;">ret</span> <br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">.</span><span style="color: #e3ceab;">try</span> <span style="color: #dcdccc;">L_0001</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #e3ceab;">catch</span> <span style="color: #dcdccc;">ConsoleUnitTest</span><span style="color: #dcdccc;">.</span><span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">handler</span> <span style="color: #dcdccc;">L_000b</span> <span style="color: #dcdccc;">to</span> <span style="color: #dcdccc;">L_000f</span><br /> <span style="color: #dcdccc;">}</span></pre>
<p>&nbsp;The definition for "rethrow" and "throw" in IL are showing below:</p>
<blockquote>
<p>rethrow: <strong>Rethrows the current exception.</strong></p>
<p>throw: <strong>Throws the exception Object currently on evaluation stack.</strong></p>
</blockquote>
<p><strong><strong>So what should we do?</strong></strong></p>
<p>Now that we are clear about the difference, what should we do? Every time we manually throw a specific type of Exception, we should wrap the caught exception as InnerException:</p>
<pre class="source" style="font-family: Consolas, 'Lucida Console', 'Courier New'; color: #dcdccc; background-color: #3f3f3f;"> <span style="color: #e3ceab;">try</span><br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span> <span style="color: #e3ceab;">new</span> <span style="color: #efef8f;">DummyException</span>(<span style="color: #cc9393;">"A dummy exception message!"</span>);<br /> <span style="color: #dcdccc;">}</span><br /> <span style="color: #e3ceab;">catch</span> (<span style="color: #dcdccc;">DummyException</span> <span style="color: #dcdccc;">de</span>)<br /> <span style="color: #dcdccc;">{</span><br /> &nbsp;&nbsp;&nbsp; <span style="color: #dcdccc;">AnotherTypeOfException</span> <span style="color: #dcdccc;">anotherTypeOfException</span> <span style="color: #dcdccc;">=</span> <span style="color: #e3ceab;">new</span> <span style="color: #dcdccc;">AnotherTypeOfException</span>(<span style="color: #cc9393;">"Customized exception message."</span><span style="color: #dcdccc;">,</span> <span style="color: #dcdccc;">de</span>)<br /> &nbsp;&nbsp;&nbsp; <span style="color: #e3ceab;">throw</span> <span style="color: #dcdccc;">anotherTypeOfException</span>;<br /> <span style="color: #dcdccc;">}</span></pre>
<p>When initializes <code>AnotherTypeOfException</code>&nbsp;we actually calls Exception's construcor "<code>(String message, Exception innerException)</code>", so finally there will be&nbsp;<strong>no information loss.</strong></p>
<p>There is one&nbsp;particular&nbsp;details,&nbsp;when we wrote code similar with below, Resharper will warning us it is redundant, because "<em>The catch statement may appear to be doing something, but it really isn't: all it's doing is throwing the exception (with the same stack information)</em>",&nbsp;<a href="http://confluence.jetbrains.net/display/ReSharper/Catch+clause+is+redundant" target="_blank">Resharper link</a>.&nbsp;</p>
<p><img src="http://www.codeproject.com/KB/Blogs/228868/RedundantThrow1.png" alt="RedundantThrow1.png" width="303" height="137" /></p>
<p><img src="http://www.codeproject.com/KB/Blogs/228868/RedundantThrow2.png" alt="RedundantThrow2.png" width="389" height="203" />&nbsp;&nbsp;</p>
<p>Instead, if we wrote "<code>throw de</code>", in the above example, Resharper will NOT give you any warning, because now we know they are different,&nbsp;"<code>throw de</code>" will&nbsp;<strong>truncate the StackTrace information and rethrow the&nbsp;<code>DemmyException&nbsp;</code>instance</strong>.&nbsp;</p>
<h3>Different between parameterless&nbsp;catch and catch (Exception ex)&nbsp;</h3>
<p>Before .NET Framework 2.0, Non-CLS-Compliant exceptions does not inherit from&nbsp;<code>System.Exception</code>, that means catch (Exception ex) cannot catch Non-CLS-Compliant exceptions thrown from for example COM or native C++ components; However, in .NET Framework 2.0, compiler will wrap those&nbsp;Non-CLS-Compliant exceptions into an specific Exception type:&nbsp;<a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.runtimewrappedexception.aspx" target="_blank">RuntimeWrappedException</a>,&nbsp;it has a property:&nbsp;<code>WrappedException</code><code>&nbsp;</code>to store a non-CLS-Compliant exception, results in statement "<code>catch (Exception ex)</code>" can catch all runtime exceptions.</p>
<p>Whereas this is configurable, the wrapping operation is by default on how ever could be turn off be applying&nbsp;<a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.runtimecompatibilityattribute.aspx" target="_blank">RuntimeCompatibility&nbsp;</a>attribute to your assembly, i.e. AssemblyInfo.cs.</p>
<pre>[assembly: RuntimeCompatibility(WrapNonExceptionThrows = false)]
</pre>
<p>By specifying WrapNonExceptionThrows = false under RuntimeCompatibility attribute, Non-CLS-Compliant exceptions will not be converted to&nbsp;<code>System.Exception</code>, so they will not be caught by catch (Exception ex) but can be caught by parameterless catch.&nbsp;&nbsp;</p>
<h3>Further reading&nbsp;&nbsp;</h3>
<p>Exception Handling on MSDN<br /><a href="http://msdn.microsoft.com/en-us/library/ms229005.aspx">http://msdn.microsoft.com/en-us/library/ms229005.aspx</a></p>
<p>Using COM Object<br /><a href="http://insideaspnet.com/index/using-com-objects/">http://insideaspnet.com/index/using-com-objects/</a>&nbsp;</p>
<p>Difference between "throw" and "throw ex" in .NET<br /><a href="http://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspx">http://geekswithblogs.net/sdorman/archive/2007/08/20/Difference-between-quotthrowquot-and-quotthrow-exquot-in-.NET.aspx</a></p>
<p>Also posted at my blog - Wayne's Geek Life:&nbsp;<br /><a href="http://wayneye.com/Blog/Different-Between-Throw-Throw-EX">http://wayneye.com/Blog/Different-Between-Throw-Throw-EX&nbsp;</a>&nbsp;</p>
<p>Also posted on CodeProject:&nbsp;<a href="http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex">http://www.codeproject.com/Articles/228868/Different-between-throw-and-throw-ex</a></p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#hack" class="page__taxonomy-item" rel="tag">Hack</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#hack" class="page__taxonomy-item" rel="tag">Hack</a>
    
    </span>
  </p>


        
          <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2011-07-08T00:00:00-07:00">July 08, 2011</time></p>
        
      </footer>

      <section class="page__share">
  
    <h4 class="page__share-title">Share on</h4>
  

  <a href="https://twitter.com/intent/tweet?via=wayneye&text=Exception+handling+particulars+in+C%23%20https%3A%2F%2Fwayneye.com%2FException-Handling-Particulars-In-Csharp" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>

  <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwayneye.com%2FException-Handling-Particulars-In-Csharp" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fwayneye.com%2FException-Handling-Particulars-In-Csharp" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>
</section>


      
  <nav class="pagination">
    
      <a href="/IE6-Should-Dead" class="pagination--pager" title="IE6çœŸè¯¥æ­»äº†
">Previous</a>
    
    
      <a href="/JavaScript-Foundation-Of-The-Language" class="pagination--pager" title="JavaScript - Foundation of the Language
">Next</a>
    
  </nav>

    </div>

    
      <div class="page__comments">
  
  
      <h4 class="page__comments-title">Leave a comment</h4>
      <section id="disqus_thread"></section>
    
</div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You may also enjoy</h4>
      <div class="grid__wrapper">
        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/Apply-UK-Visit-VISA" rel="permalink">Apply UK Visit VISA
</a>
      
    </h2>
    
      <p class="page__meta"><i class="far fa-clock" aria-hidden="true"></i> 




  4 minute read
</p>
    
    <p class="archive__item-excerpt" itemprop="description">Background

</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/Master-AWS-Development-Video-Published" rel="permalink">Master AWS Development Video Published
</a>
      
    </h2>
    
      <p class="page__meta"><i class="far fa-clock" aria-hidden="true"></i> 




  2 minute read
</p>
    
    <p class="archive__item-excerpt" itemprop="description">Publishing information

</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/self-improvement/passing-aws-certified-solutions-architect/" rel="permalink">Passing AWS Certified Solutions Architect
</a>
      
    </h2>
    
      <p class="page__meta"><i class="far fa-clock" aria-hidden="true"></i> 




  1 minute read
</p>
    
    <p class="archive__item-excerpt" itemprop="description">

</p>
  </article>
</div>

        
          



<div class="grid__item">
  <article class="archive__item" itemscope itemtype="https://schema.org/CreativeWork">
    
    <h2 class="archive__item-title" itemprop="headline">
      
        <a href="/geek/Storage-Media-Home-Server-Less-Than-300/" rel="permalink">Storage+Media home server for less than $300
</a>
      
    </h2>
    
      <p class="page__meta"><i class="far fa-clock" aria-hidden="true"></i> 




  1 minute read
</p>
    
    <p class="archive__item-excerpt" itemprop="description">Background
I have been researched and watched many NAS options to setup a home storage+media server during the past year, and so far there was no perfect ans...</p>
  </article>
</div>

        
      </div>
    </div>
  
  
</div>

    </div>

    

    <div class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    
      <li><strong>Follow:</strong></li>
    

    
      
        
          <li><a href="mailto:admin@wayneye.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
        
          <li><a href="https://wayneye.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-link" aria-hidden="true"></i> Website</a></li>
        
      
        
          <li><a href="https://twitter.com/wayneye" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-twitter-square" aria-hidden="true"></i> Twitter</a></li>
        
      
        
          <li><a href="https://facebook.com/WayneYeDotCom" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
          <li><a href="https://github.com/WayneYe/" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2019 Wayne Ye. Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>.</div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>







    
  <script>
    var disqus_config = function () {
      this.page.url = "https://wayneye.com/Exception-Handling-Particulars-In-Csharp";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "/Exception-handling-particulars-in-C#"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://wayneye.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


  





  </body>
</html>
